# Generated by Django 4.2 on 2024-03-19 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_job_address_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='phone_company',
        ),
    ]
